# Generated by Django 5.1.7 on 2025-04-19 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_company_url_company_domain_and_more'),
        ('source', '0003_alter_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='company.company'),
        ),
    ]
