# Generated by Django 5.0.13 on 2025-03-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0001_initial'),
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='css',
            name='tagged_companies',
            field=models.ManyToManyField(blank=True, related_name='tagged_stories', to='company.company'),
        ),
    ]
