# Generated by Django 5.0.13 on 2025-04-01 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('source', '0002_source_tagged_companies'),
        ('story', '0002_story_tagged_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='css',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='stories', to='source.source'),
        ),
    ]
