# Generated by Django 5.0.13 on 2025-04-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0002_rename_company_url_company_domain_and_more'),
        ('story', '0003_alter_story_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='css',
            name='article_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='css',
            name='tagged_companies',
            field=models.ManyToManyField(blank=True, null=True, related_name='tagged_stories', to='company.company'),
        ),
    ]
